### PR TITLE
aarch64, ppc64le, Profiles for secondary archs, Linux and Linux with Android NDK installed

### PR DESCRIPTION
**Pull request by Karm**
This PR surpasses and completes #7 , which can be closed.

### CODE REVIEW

**Comment by Karm** [comment]
?

**Comment by bp-alex** [comment]
Thanks @Karm for this PR. Please accept my apologies for the delay in reviewing it (and its predecessor #7).

At present [we use](https://github.com/lmdbjava/native/blob/master/.github/workflows/maven.yml) GitHub Actions to compile or cross-compile the LMDB native library for all architectures defined in the [LmdbJava Native Parent POM](https://github.com/lmdbjava/native/blob/master/pom.xml). Maintaining automatic, reproducible builds with public build logs is a priority given it significantly simplifies long-term maintenance of the LmdbJava project while also offering everyone reassurance as to the test suite verification and binary contents of JARs automatically deployed to Maven Central.

Given the benefits of using GitHub Actions to build and compile the native libraries, I wonder whether you might be able to comment on the viability of a cross-compilation option? I did a quick search and found several GitHub Actions YAML files which are using various cross-compilation approaches for aarch64 and ppc64le. There is also a GitHub Action called  [run-on-arch-action](https://github.com/uraimo/run-on-arch-action) which is currently targeting [five platforms](https://github.com/uraimo/run-on-arch-action) including aarch64 and ppc64le.

If you could offer some comments on this I would appreciate it.

**Comment by bp-alex** [comment]
I added an extra operating system (Arch Linux) to several [run-on-arch-action](https://github.com/uraimo/run-on-arch-action) platforms and started using it in [another project](https://github.com/benalexau/aur-repo). I believe `run-on-arch-action` is the preferred way to add additional platform / OS combinations. I will take a closer look at this when I get some free cycles.

**Comment by bp-alex** [comment]
Closing this ticket as https://github.com/lmdbjava/lmdbjava/pull/217 has provided a Zig-based cross-compilation in the Java module product. This in turn means the LmdbJava Native project is no longer required and will be archived.

I welcome contributions in the LmdbJava project if you wish to revisit this based on the new Zig-based cross-compiled builds (which include ARM targets).

**Pull request closed without merging**
